export const SET_ALL_FILMS = "SET_ALL_FILMS";
export const FILMS_LOADING = "FILMS_LOADING";
export const FILMS_ERROR = "FILMS_ERROR";
export const LIKE_MOVIE = "LIKE_MOVIE";
export const INPUT_SEARCH = "INPUT_SEARCH";
export const ERROR_COMMETS = "ERROR_COMMETS";
export const LOADING_COMMETS = "LOADING_COMMETS";
export const LOADING_COMMETS_DELETE = "LOADING_COMMETS_DELETE";
