export const USER_LOADING = "USER_LOADING";
export const USER_DELETE_LOADING = "USER_DELETE_LOADING";
export const USER_MESSAGES_SUCCESS = "USER_MESSAGES_SUCCESS";
export const USER_MESSAGES_ERROR = "USER_MESSAGES_ERROR";
export const RESET_USER_ALERT = "RESET_USER_ALERT";
export const SET_INPUT = "SET_INPUT";
export const SET_INPUT_REQUIRED = "SET_INPUT_REQUIRED";
